=== LucasPrezFdez/HTML/HTML_2eva/examen/ejercicio2B.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- Defino la clase raiz -->
    <xs:element name="herbologia">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="arbol" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Defino el elemento arbol -->
    <xs:element name="arbol">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="NombreLatin" />
                <xs:element ref="NombreComun" />
                <xs:element ref="Vegetaci칩n" />
                <xs:element ref="Altura" />
                <xs:element ref="FormaYEstructura" />
                <xs:element ref="ColorEnPrimavera" />
                <xs:element ref="ColorEnOto침o" minOccurs="0" />
                <xs:element ref="ResistenciaALasHeladas" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Todos los elementos de arbol -->
    <xs:element name="NombreLatin" type="xs:string" />
    <xs:element name="NombreComun" type="xs:string" />
    <xs:element name="Vegetaci칩n" type="xs:string" />
    <xs:element name="Altura" type="xs:string" />
    <xs:element name="FormaYEstructura" type="xs:string" />
    <xs:element name="ColorEnPrimavera" type="xs:string" />
    <xs:element name="ColorEnOto침o" type="xs:string" />
    <xs:element name="ResistenciaALasHeladas" type="xs:string" />
</xs:schema>

=== LucasPrezFdez/HTML/HTML_2eva/examen/ejercicio2B.xml
<?xml version="1.0" encoding="UTF-8"?>
<herbologia xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="ejercicio2B.xsd">

    <arbol>
        <NombreLatin>Fagus sylvatica</NombreLatin>
        <NombreComun>Haya</NombreComun>
        <Vegetación>Caducifolio</Vegetación>
        <Altura>De 30 a 35 metros</Altura>
        <FormaYEstructura> Copa cónica o redondeada. Tronco principal recto. Ramaje ascendente</FormaYEstructura>
        <ColorEnPrimavera>Haz verde claro brillante, envés verde pálido</ColorEnPrimavera>
        <ColorEnOtoño>Amarillo dorado a marrón rojizo</ColorEnOtoño>
        <ResistenciaALasHeladas>Heladas muy fuertes (hasta -25ºC)</ResistenciaALasHeladas>
    </arbol>
    <arbol>
        <NombreLatin>Pinus pinea</NombreLatin>
        <NombreComun> Pino piñonero</NombreComun>
        <Vegetación>Perenne</Vegetación>
        <Altura>De 20 a 30 metros</Altura>
        <FormaYEstructura> Copa aparasolada. Tronco principal recto. Ramaje extendido</FormaYEstructura>
        <ColorEnPrimavera>Verde oscuro</ColorEnPrimavera>
        <ResistenciaALasHeladas>Heladas medias (hasta -10ºC)</ResistenciaALasHeladas>
    </arbol>
    <arbol>
        <NombreLatin>Betula pendula</NombreLatin>
        <NombreComun>Abedul</NombreComun>
        <Vegetación>Caducifolio</Vegetación>
        <Altura> De 15 a 20 metros</Altura>
        <FormaYEstructura>Copa piramidal. Tronco principal recto. Ramaje colgante</FormaYEstructura>
        <ColorEnPrimavera>Verde claro brillante</ColorEnPrimavera>
        <ColorEnOtoño>Amarillo dorado</ColorEnOtoño>
        <ResistenciaALasHeladas>Heladas muy fuertes (hasta -30ºC)</ResistenciaALasHeladas>
    </arbol>
    <arbol>
        <NombreLatin>Cedrus atlantica</NombreLatin>
        <NombreComun>Cedro del Atlas</NombreComun>
        <Vegetación>Perenne</Vegetación>
        <Altura>De 30 a 40 metros</Altura>
        <FormaYEstructura>Copa cónica. Tronco principal recto. Ramaje horizontal</FormaYEstructura>
        <ColorEnPrimavera>Verde azulado</ColorEnPrimavera>
        <ResistenciaALasHeladas>Heladas fuertes (hasta -20ºC)</ResistenciaALasHeladas>
    </arbol>
</herbologia>
