=== LucasPrezFdez/HTML/HTML_2eva/examen/ejercicio1B.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- Defino la clase raiz -->
    <xs:element name="coleccion">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="dvd" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Defino el elemento dvd -->
    <xs:element name="dvd">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="titulo" />
                <xs:element ref="director" />
                <xs:element ref="anio" />
                <xs:element ref="genero" />
                <xs:element ref="duracion" />
                <xs:element ref="formato" />
            </xs:sequence>
            <!-- Atributos de dvd -->
            <xs:attribute name="id" use="required" />
            <xs:attribute name="idioma" use="required" />
        </xs:complexType>
    </xs:element>

    <!-- Todos los elementos de dvd -->
    <xs:element name="titulo" type="xs:string" />
    <xs:element name="director" type="xs:string" />
    <xs:element name="anio" type="xs:integer" />
    <xs:element name="genero" type="xs:string" />
    <xs:element name="duracion" type="xs:integer" />
    <xs:element name="formato" type="xs:string" />
</xs:schema>

=== LucasPrezFdez/HTML/HTML_2eva/examen/ejercicio1B.xml
<?xml version="1.0" encoding="UTF-8"?>
<coleccion xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="ejercicio1B.xsd">

    <dvd id="1" idioma="español">
        <titulo>El Señor de los Anillos: La Comunidad del Anillo</titulo>
        <director>Peter Jackson</director>
        <anio>2001</anio>
        <genero>Fantasía</genero>
        <duracion>178</duracion>
        <formato>Blu-ray</formato>
    </dvd>

    <dvd id="2" idioma="inglés">
        <titulo>Inception</titulo>
        <director>Christopher Nolan</director>
        <anio>2010</anio>
        <genero>Ciencia ficción</genero>
        <duracion>148</duracion>
        <formato>DVD</formato>
    </dvd>

    <dvd id="3" idioma="italiano">
        <titulo>La vida es bella</titulo>
        <director>Roberto Benigni</director>
        <anio>1997</anio>
        <genero>Comedia dramática</genero>
        <duracion>116</duracion>
        <formato>4K Ultra HD</formato>
    </dvd>

    <dvd id="4" idioma="francés">
        <titulo>Amélie</titulo>
        <director>Jean-Pierre Jeunet</director>
        <anio>2001</anio>
        <genero>Comedia romántica</genero>
        <duracion>122</duracion>
        <formato>Blu-ray</formato>
    </dvd>

    <dvd id="5" idioma="español">
        <titulo>El laberinto del fauno</titulo>
        <director>Guillermo del Toro</director>
        <anio>2006</anio>
        <genero>Fantasía oscura</genero>
        <duracion>118</duracion>
        <formato>DVD</formato>
    </dvd>
</coleccion>
